'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Familiar.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AGear118() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AGear118", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AGear1181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AGear1181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabArrow_Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabArrow_Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabGear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabGear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabGear_Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabGear_Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabHyphen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabHyphen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabHyphen_Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabHyphen_Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabPlus_Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabPlus_Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AltTabPlus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AltTabPlus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackOfAddressBook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackOfAddressBook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackOfAddressBook_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackOfAddressBook_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blackback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueGradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueGradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cbback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cbback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChalkyPentelecIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChalkyPentelecIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Chicago_Blackhawks_2012_Goal_Horn__HQ_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicago_Blackhawks_2012_Goal_Horn__HQ_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chrysler_Building_Midtown_Manhattan_New_York_City_1932() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chrysler_Building_Midtown_Manhattan_New_York_City_1932", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ctryk9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ctryk9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeleteUnContact1302013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteUnContact1302013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dwncsv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dwncsv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Enter1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enter1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Enter2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enter2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FacebookDialogPopUpBk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FacebookDialogPopUpBk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fwd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fwd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property germanshepherd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("germanshepherd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Golden_Labrador_by_shiningstar25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Golden_Labrador_by_shiningstar25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayGradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayGradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayToWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayToWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayToWhite1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayToWhite1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayToWhite2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayToWhite2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greenchk_circ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenchk_circ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iampeas_gshep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iampeas_gshep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image006() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image006", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_fb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_fb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IncreaseViewSizeSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncreaseViewSizeSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IncreaseViewSizeUnselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncreaseViewSizeUnselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IsThis218() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IsThis218", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LEWUTORANGENOVIKT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LEWUTORANGENOVIKT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magnet1_RJ_1027() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magnet1_RJ_1027", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_york_city() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_york_city", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NO_THEREISNOPHOTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NO_THEREISNOPHOTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nuevo_LtBlA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nuevo_LtBlA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nuevo_LtBlA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nuevo_LtBlA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nuevo219() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuevo219", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Oceanwallpaper2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oceanwallpaper2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OCRFamiliar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OCRFamiliar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property old_baseball_4620() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("old_baseball_4620", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oriel_webpages_physics_VirgoSlice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oriel_webpages_physics_VirgoSlice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PaperCrinklePaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCrinklePaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paperhires() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paperhires", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PentelecFamiliarDevSplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PentelecFamiliarDevSplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PentelecFamiliarDevSplash_13120131624hrs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PentelecFamiliarDevSplash_13120131624hrs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PentelecIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PentelecIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plec_leather020041511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plec_leather020041511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plec_leather0200415111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plec_leather0200415111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PlusAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlusAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PlusModeNine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlusModeNine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PossibleSaveLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PossibleSaveLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postitle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postitle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postoppart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postoppart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionMark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionMark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionMarkSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionMarkSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionModeNine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionModeNine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Selected_DeleteUnContact1302013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selected-DeleteUnContact1302013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Selected_GoToLeather() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selected-GoToLeather", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Selected_ThatsAPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selected-ThatsAPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skype() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skype", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skype_Revised() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skype-Revised", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SlimVersion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlimVersion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwitchToLeather() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwitchToLeather", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempLogoFamiliar712012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempLogoFamiliar712012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThatsAPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThatsAPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property thumb_bazzillwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thumb_bazzillwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TimesSquareNYC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimesSquareNYC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Toolbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toolbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property w139681376() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w139681376", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property w1396813761() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w1396813761", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatMail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatMail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatMailRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatMailRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatNewFamiliarGASPLogo218() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatNewFamiliarGASPLogo218", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatNewFamiliarGASPLogo2181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatNewFamiliarGASPLogo2181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowOrange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowOrange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
